name = "ocr-checks-worker"
main = "src/index.ts"
compatibility_date = "2024-04-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Logging is enabled by default in Workers
# Debug level is used for development

# Global limits (paid plan required)
[limits]
cpu_ms = 50  # Default CPU time limit in milliseconds
duration_ms = 30000  # Default maximum execution time (30 seconds)

# Development environment (remote Workers deployment)
[env.dev]
name = "ocr-checks-worker-dev"
workers_dev = true
vars = { ENVIRONMENT = "development", MISTRAL_DEBUG = true, JSON_EXTRACTOR_TYPE = "cloudflare" }
ai = { binding = "AI" }

# With the paid plan, we can now set higher limits
[env.dev.limits]
cpu_ms = 50  # Default CPU time limit in milliseconds
duration_ms = 60000  # Increased to 60 seconds for complex OCR + JSON extraction

# Staging environment
[env.staging]
name = "ocr-checks-worker-staging"
# Removing custom domain route to use workers.dev subdomain only
# route = "staging-api.nolock.social/*"
workers_dev = true
vars = { ENVIRONMENT = "staging", MISTRAL_DEBUG = true, JSON_EXTRACTOR_TYPE = "cloudflare" }
ai = { binding = "AI" }

# Staging environment limits
[env.staging.limits]
cpu_ms = 50  # Default CPU time limit in milliseconds
duration_ms = 60000  # Increased to 60 seconds for complex OCR + JSON extraction

# Production environment
[env.production]
name = "ocr-checks-worker"
workers_dev = true
# IMPORTANT: Do not store API keys here, use secrets instead
vars = { ENVIRONMENT = "production", MISTRAL_DEBUG = false, JSON_EXTRACTOR_TYPE = "cloudflare" }
ai = { binding = "AI" }

# Production environment limits
[env.production.limits]
cpu_ms = 50  # Default CPU time limit in milliseconds
duration_ms = 60000  # Increased to 60 seconds for complex OCR + JSON extraction

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# Environment variables
# IMPORTANT: DO NOT ADD API KEYS HERE!
# Use Cloudflare Worker secrets instead: wrangler secret put MISTRAL_API_KEY
# Example: echo "your-api-key" | wrangler secret put MISTRAL_API_KEY
# Global variables that apply to all environments have been moved to the environment-specific sections

# JSON Extractor Configuration:
# - Remote environments (dev, staging, production): Use Cloudflare Llama 3.3 (JSON_EXTRACTOR_TYPE=cloudflare)
# - Local development (wrangler dev): Uses Mistral API (no JSON_EXTRACTOR_TYPE set, defaults to 'mistral')