name: CI

on:
  push:
    branches: 
      - develop
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches: 
      - develop
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run unit tests
        run: npm run test:unit -- --bypass-gitflow-check
        
      - name: Run functional tests
        run: npm run test:functional -- --bypass-gitflow-check
        
      # Semi-integration tests require API key, skip if not available
      - name: Run semi-integration tests
        run: npm run test:semi -- --bypass-gitflow-check
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        continue-on-error: true