name: Deploy to Development

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  deploy:
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run unit tests
        run: npx tsx scripts/run-unit-tests-tsx.ts --bypass-gitflow-check
      
      - name: Create .dev.vars file
        run: |
          echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}" > .dev.vars
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> .dev.vars
      
      - name: Deploy to dev environment
        run: npm run deploy:dev
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          
      - name: Notify deployment success
        if: success()
        run: |
          echo "Deployment to dev environment successful"
          echo "API is now available at https://dev-api.nolock.social"