name: Deploy to Staging

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm test
      
      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: staging
          preCommands: |
            echo "Deploying to staging environment..."
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          
      - name: Notify deployment success
        if: success()
        run: |
          echo "Deployment to staging environment successful"
          echo "API is now available at https://staging-api.nolock.social"