name: Deploy to Development

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  deploy:
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Set Cloudflare Worker secrets
        run: |
          echo "${{ secrets.MISTRAL_API_KEY }}" | wrangler secret put MISTRAL_API_KEY --env dev
          echo "${{ secrets.CLOUDFLARE_API_TOKEN }}" | wrangler secret put CLOUDFLARE_API_TOKEN --env dev
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: dev
          preCommands: |
            echo "Deploying to dev environment..."
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          
      - name: Notify deployment success
        if: success()
        run: |
          echo "Deployment to dev environment successful"
          echo "API is now available at https://dev-api.nolock.social"